version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 84:80
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    volumes:
      - ./mysql_data:/var/lib/mysql

  python:
    image: python:latest
    volumes:
      - ./python_app:/app
    working_dir: /app
    command: tail -f /dev/null